import type { Call } from "@/lib/types/calls";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_CALLS: Call[] = [
  {
    id: "call-001",
    business_id: null,
    caller_name: "Sarah Mitchell",
    phone_number: "(512) 555-0134",
    service_requested: "AC Unit Replacement",
    duration: 263,
    lead_score: "HOT",
    deal_intent_score: 9,
    confidence_level: "HIGH",
    price_comfort_low: 3500,
    price_comfort_high: 5000,
    recommendation: "Follow up within 2 hours — ready to buy",
    status: "new",
    is_read: false,
    created_at: hoursAgo(2),
  },
  {
    id: "call-002",
    business_id: null,
    caller_name: null,
    phone_number: "(512) 555-0189",
    service_requested: "Pest Inspection",
    duration: 105,
    lead_score: "WARM",
    deal_intent_score: 5,
    confidence_level: "MEDIUM",
    price_comfort_low: 100,
    price_comfort_high: 250,
    recommendation: "Send pricing info via text",
    status: "new",
    is_read: false,
    created_at: hoursAgo(3),
  },
  {
    id: "call-003",
    business_id: null,
    caller_name: "James Rodriguez",
    phone_number: "(512) 555-0156",
    service_requested: "Roof Leak Repair",
    duration: 312,
    lead_score: "HOT",
    deal_intent_score: 8,
    confidence_level: "HIGH",
    price_comfort_low: 800,
    price_comfort_high: 2000,
    recommendation: "Schedule estimate visit this week",
    status: "new",
    is_read: false,
    created_at: hoursAgo(5),
  },
  {
    id: "call-004",
    business_id: null,
    caller_name: "Maria Chen",
    phone_number: "(512) 555-0198",
    service_requested: "Teeth Whitening",
    duration: 150,
    lead_score: "COLD",
    deal_intent_score: 3,
    confidence_level: "LOW",
    price_comfort_low: 100,
    price_comfort_high: 200,
    recommendation: "Add to nurture sequence",
    status: "new",
    is_read: true,
    created_at: daysAgo(1),
  },
  {
    id: "call-005",
    business_id: null,
    caller_name: "David Park",
    phone_number: "(512) 555-0167",
    service_requested: "Emergency Plumbing",
    duration: 75,
    lead_score: "HOT",
    deal_intent_score: 9,
    confidence_level: "HIGH",
    price_comfort_low: 200,
    price_comfort_high: 500,
    recommendation: "Urgent — dispatch immediately",
    status: "new",
    is_read: true,
    created_at: daysAgo(1),
  },
  {
    id: "call-006",
    business_id: null,
    caller_name: "Lisa Thompson",
    phone_number: "(512) 555-0145",
    service_requested: "Termite Treatment",
    duration: 230,
    lead_score: "WARM",
    deal_intent_score: 6,
    confidence_level: "MEDIUM",
    price_comfort_low: 300,
    price_comfort_high: 600,
    recommendation: "Send treatment plan options",
    status: "new",
    is_read: true,
    created_at: daysAgo(1),
  },
  {
    id: "call-007",
    business_id: null,
    caller_name: "Robert Kim",
    phone_number: "(512) 555-0178",
    service_requested: "Personal Injury Consultation",
    duration: 380,
    lead_score: "HOT",
    deal_intent_score: 10,
    confidence_level: "HIGH",
    price_comfort_low: 5000,
    price_comfort_high: 15000,
    recommendation: "High-value lead — partner call today",
    status: "new",
    is_read: true,
    created_at: daysAgo(2),
  },
  {
    id: "call-008",
    business_id: null,
    caller_name: "Amy Foster",
    phone_number: "(512) 555-0123",
    service_requested: "Annual HVAC Maintenance",
    duration: 130,
    lead_score: "COLD",
    deal_intent_score: 2,
    confidence_level: "LOW",
    price_comfort_low: 75,
    price_comfort_high: 150,
    recommendation: "Add to seasonal maintenance list",
    status: "new",
    is_read: true,
    created_at: daysAgo(2),
  },
  {
    id: "call-009",
    business_id: null,
    caller_name: "Tom Wright",
    phone_number: "(512) 555-0190",
    service_requested: "Dental Crown",
    duration: 215,
    lead_score: "WARM",
    deal_intent_score: 7,
    confidence_level: "MEDIUM",
    price_comfort_low: 800,
    price_comfort_high: 1500,
    recommendation: "Schedule consultation with Dr. Adams",
    status: "new",
    is_read: true,
    created_at: daysAgo(3),
  },
  {
    id: "call-010",
    business_id: null,
    caller_name: "Karen Davis",
    phone_number: "(512) 555-0112",
    service_requested: "Carpenter Ant Removal",
    duration: 175,
    lead_score: "WARM",
    deal_intent_score: 5,
    confidence_level: "MEDIUM",
    price_comfort_low: 200,
    price_comfort_high: 400,
    recommendation: "Send inspection scheduling link",
    status: "new",
    is_read: true,
    created_at: daysAgo(3),
  },
];
